package com.grandtech

import com.grandtech.auth.Authenticated
import com.grandtech.model.Room
import com.grandtech.model.RoomCapabilityTag
import com.grandtech.service.RoomService
import com.grandtech.service.SchoolService
import com.grandtech.utils.ApiResponse
import io.quarkus.logging.Log
import jakarta.inject.Inject
import jakarta.ws.rs.Consumes
import jakarta.ws.rs.DELETE
import jakarta.ws.rs.GET
import jakarta.ws.rs.PATCH
import jakarta.ws.rs.POST
import jakarta.ws.rs.Path
import jakarta.ws.rs.PathParam
import jakarta.ws.rs.Produces
import jakarta.ws.rs.container.ContainerRequestContext
import jakarta.ws.rs.core.Context
import jakarta.ws.rs.core.MediaType

/** REST resource exposing room management endpoints for the Zentro API. */
@Path("/school/room")
class RoomResource {

    @Inject
    /** Verifies that the authenticated user owns a school before room operations. */
    lateinit var schoolService: SchoolService

    @Inject
    /** Handles Neo4j read and write operations for [com.grandtech.model.Room] nodes. */
    lateinit var roomService: RoomService

    /**
     * Lists all room capability tags supported by the system.
     *
     * Intended for front-end dropdowns when creating specialist rooms.
     *
     * @return an [ApiResponse] whose payload is the list of capability tag names
     */
    @GET
    @Path("/capability-tags")
    @Produces(MediaType.APPLICATION_JSON)
    fun listRoomCapabilityTags(): ApiResponse<List<String>> {
        Log.info("listRoomCapabilityTags()---->")
        return ApiResponse(200, "Success", RoomCapabilityTag.entries.map { it.name })
    }

    /**
     * Creates a new room and associates it with the authenticated school.
     *
     * The room's [Room.id] is generated by Neo4j — clients must not supply one.
     */
    @POST
    @Path("/create")
    @Authenticated
    @Consumes(MediaType.APPLICATION_JSON)
    @Produces(MediaType.APPLICATION_JSON)
    fun createRoom(
        @Context requestContext: ContainerRequestContext,
        room: Room,
    ): ApiResponse<Room> {
        Log.info("createRoom()---->")
        val fedUid = requestContext.getProperty("fedUid") as String
        schoolService.getSchoolByFedUid(fedUid)
            ?: return ApiResponse(403, "Forbidden: account is not a school", null)
        val created = roomService.createRoom(fedUid, room)
        return if (created != null) {
            ApiResponse(200, "Room created", created)
        } else {
            ApiResponse(404, "School not found", null)
        }
    }

    /**
     * Lists all rooms belonging to the authenticated school, ordered by name.
     */
    @GET
    @Path("/list")
    @Authenticated
    @Produces(MediaType.APPLICATION_JSON)
    fun listRooms(@Context requestContext: ContainerRequestContext): ApiResponse<List<Room>> {
        Log.info("listRooms()---->")
        val fedUid = requestContext.getProperty("fedUid") as String
        schoolService.getSchoolByFedUid(fedUid)
            ?: return ApiResponse(403, "Forbidden: account is not a school", null)
        return ApiResponse(200, "Success", roomService.listRooms(fedUid))
    }

    /**
     * Updates the mutable fields of a room owned by the authenticated school.
     *
     * [Room.id] is immutable and is taken from the path. Omitting a field (null)
     * leaves the existing stored value unchanged.
     */
    @PATCH
    @Path("/update/{id}")
    @Authenticated
    @Consumes(MediaType.APPLICATION_JSON)
    @Produces(MediaType.APPLICATION_JSON)
    fun updateRoom(
        @Context requestContext: ContainerRequestContext,
        @PathParam("id") id: String,
        room: Room,
    ): ApiResponse<Room> {
        Log.info("updateRoom()---->")
        val fedUid = requestContext.getProperty("fedUid") as String
        schoolService.getSchoolByFedUid(fedUid)
            ?: return ApiResponse(403, "Forbidden: account is not a school", null)
        val updated = roomService.updateRoom(fedUid, id, room)
        return if (updated != null) {
            ApiResponse(200, "Room updated", updated)
        } else {
            ApiResponse(404, "Room not found", null)
        }
    }

    /**
     * Deletes a room owned by the authenticated school.
     *
     * The room is only deleted when it is linked to this school via a `HAS_ROOM`
     * relationship, preventing one school from deleting another school's rooms.
     */
    @DELETE
    @Path("/delete/{id}")
    @Authenticated
    @Produces(MediaType.APPLICATION_JSON)
    fun deleteRoom(
        @Context requestContext: ContainerRequestContext,
        @PathParam("id") id: String,
    ): ApiResponse<Nothing> {
        Log.info("deleteRoom()---->")
        val fedUid = requestContext.getProperty("fedUid") as String
        schoolService.getSchoolByFedUid(fedUid)
            ?: return ApiResponse(403, "Forbidden: account is not a school", null)
        val deleted = roomService.deleteRoom(fedUid, id)
        return if (deleted) {
            ApiResponse(200, "Room deleted", null)
        } else {
            ApiResponse(404, "Room not found", null)
        }
    }
}