package com.grandtech

import com.grandtech.auth.Authenticated
import com.grandtech.model.Room
import com.grandtech.model.RoomCapabilityTag
import com.grandtech.model.School
import com.grandtech.model.Subject
import com.grandtech.service.SchoolService
import com.grandtech.service.SubjectRepository
import com.grandtech.utils.ApiResponse
import jakarta.inject.Inject
import jakarta.ws.rs.Consumes
import jakarta.ws.rs.DELETE
import jakarta.ws.rs.GET
import jakarta.ws.rs.PATCH
import jakarta.ws.rs.POST
import jakarta.ws.rs.Path
import jakarta.ws.rs.PathParam
import jakarta.ws.rs.Produces
import jakarta.ws.rs.container.ContainerRequestContext
import jakarta.ws.rs.core.Context
import jakarta.ws.rs.core.MediaType

/** REST resource exposing school-related endpoints for the Zentro API. */
@Path("/schools")
class SchoolResource {

    /** Repository that queries Neo4j for subject and subject-type nodes. */
    @Inject
    lateinit var subjectRepository: SubjectRepository

    /** Service that executes school-specific Neo4j queries. */
    @Inject
    lateinit var schoolService: SchoolService

    /**
     * Returns a confirmation that the schools endpoint is reachable.
     *
     * @return an [ApiResponse] with a status message as payload
     */
    @GET
    @Produces(MediaType.APPLICATION_JSON)
    fun getSchools(): ApiResponse<String> = ApiResponse(200, "success", "Schools endpoint is live")

    /**
     * Lists all CBC JSS subjects.
     *
     * Data is seeded at startup and reflects the subjects defined by the Kenya
     * Institute of Curriculum Development (KICD) for Grades 7–9.
     *
     * @return an [ApiResponse] whose payload is a list of [Subject] objects.
     */
    @GET
    @Path("/subjects")
    @Produces(MediaType.APPLICATION_JSON)
    fun listSubjects(): ApiResponse<List<Subject>> =
        ApiResponse(200, "Success", subjectRepository.listAll())

    /**
     * Returns the authenticated school's profile.
     *
     * The [Authenticated] guard verifies the bearer token and ensures the Firebase
     * UID belongs to a registered user before this handler runs. The UID is then
     * used to fetch the [School] node directly from Neo4j.
     *
     * @param requestContext the JAX-RS request context carrying the `fedUid` property
     *                       set by [com.grandtech.auth.AuthFilter]
     * @return an [ApiResponse] carrying the [School] on success, or 403 if the token
     *         belongs to a non-school account
     */
    @GET
    @Path("/profile")
    @Authenticated
    @Produces(MediaType.APPLICATION_JSON)
    fun getSchoolDetails(@Context requestContext: ContainerRequestContext): ApiResponse<School> {
        val fedUid = requestContext.getProperty("fedUid") as String
        val school = schoolService.getSchoolByFedUid(fedUid)
        return if (school != null) {
            ApiResponse(200, "Success", school)
        } else {
            ApiResponse(403, "Forbidden: account is not a school", null)
        }
    }


    /**
     * Lists all room capability tags supported by the system.
     *
     * Intended for front-end dropdowns when creating specialist rooms. The values
     * correspond to [RoomCapabilityTag] enum entries and are returned as strings.
     *
     * @return an [ApiResponse] whose payload is the list of capability tag names
     */
    @GET
    @Path("/rooms/capability-tags")
    @Produces(MediaType.APPLICATION_JSON)
    fun listRoomCapabilityTags(): ApiResponse<List<String>> =
        ApiResponse(200, "Success", RoomCapabilityTag.entries.map { it.name })

    /**
     * Creates a new room and associates it with the authenticated school.
     *
     * The room's [Room.id] is generated by Neo4j — clients must not supply one.
     * Only school accounts may call this endpoint; a teacher token returns 403.
     *
     * @param requestContext the JAX-RS request context carrying the `fedUid` set by [com.grandtech.auth.AuthFilter]
     * @param room           the room data to persist
     * @return an [ApiResponse] carrying the created [Room] on success, or 403 if the
     *         token does not belong to a school account
     */
    @POST
    @Path("/rooms")
    @Authenticated
    @Consumes(MediaType.APPLICATION_JSON)
    @Produces(MediaType.APPLICATION_JSON)
    fun createRoom(
        @Context requestContext: ContainerRequestContext,
        room: Room,
    ): ApiResponse<Room> {
        val fedUid = requestContext.getProperty("fedUid") as String
        schoolService.getSchoolByFedUid(fedUid)
            ?: return ApiResponse(403, "Forbidden: account is not a school", null)
        val created = schoolService.createRoom(fedUid, room)
        return if (created != null) {
            ApiResponse(200, "Room created", created)
        } else {
            ApiResponse(404, "School not found", null)
        }
    }

    /**
     * Lists all rooms belonging to the authenticated school, ordered by name.
     *
     * @param requestContext the JAX-RS request context carrying the `fedUid` set by [com.grandtech.auth.AuthFilter]
     * @return an [ApiResponse] whose payload is the list of [Room] objects, or 403 if the
     *         token does not belong to a school account
     */
    @GET
    @Path("/rooms")
    @Authenticated
    @Produces(MediaType.APPLICATION_JSON)
    fun listRooms(@Context requestContext: ContainerRequestContext): ApiResponse<List<Room>> {
        val fedUid = requestContext.getProperty("fedUid") as String
        schoolService.getSchoolByFedUid(fedUid)
            ?: return ApiResponse(403, "Forbidden: account is not a school", null)
        return ApiResponse(200, "Success", schoolService.listRooms(fedUid))
    }

    /**
     * Updates the mutable fields of a room owned by the authenticated school.
     *
     * [Room.id] is immutable and is taken from the path, not the request body.
     * Omitting a field (null) leaves the existing stored value unchanged.
     *
     * @param requestContext the JAX-RS request context carrying the `fedUid` set by [com.grandtech.auth.AuthFilter]
     * @param id             the UUID of the room to update
     * @param room           the new field values
     * @return an [ApiResponse] carrying the updated [Room] on success, 403 if the token does
     *         not belong to a school, or 404 if no room with the given id exists in this school
     */
    @PATCH
    @Path("/rooms/{id}")
    @Authenticated
    @Consumes(MediaType.APPLICATION_JSON)
    @Produces(MediaType.APPLICATION_JSON)
    fun updateRoom(
        @Context requestContext: ContainerRequestContext,
        @PathParam("id") id: String,
        room: Room,
    ): ApiResponse<Room> {
        val fedUid = requestContext.getProperty("fedUid") as String
        schoolService.getSchoolByFedUid(fedUid)
            ?: return ApiResponse(403, "Forbidden: account is not a school", null)
        val updated = schoolService.updateRoom(fedUid, id, room)
        return if (updated != null) {
            ApiResponse(200, "Room updated", updated)
        } else {
            ApiResponse(404, "Room not found", null)
        }
    }

    /**
     * Deletes a room owned by the authenticated school.
     *
     * The room is only deleted when it is linked to this school via a `HAS_ROOM`
     * relationship, preventing one school from deleting another school's rooms.
     *
     * @param requestContext the JAX-RS request context carrying the `fedUid` set by [com.grandtech.auth.AuthFilter]
     * @param id             the UUID of the room to delete
     * @return an [ApiResponse] with 200 on success, 403 if the token is not a school,
     *         or 404 if no matching room was found under this school
     */
    @DELETE
    @Path("/rooms/{id}")
    @Authenticated
    @Produces(MediaType.APPLICATION_JSON)
    fun deleteRoom(
        @Context requestContext: ContainerRequestContext,
        @PathParam("id") id: String,
    ): ApiResponse<Nothing> {
        val fedUid = requestContext.getProperty("fedUid") as String
        schoolService.getSchoolByFedUid(fedUid)
            ?: return ApiResponse(403, "Forbidden: account is not a school", null)
        val deleted = schoolService.deleteRoom(fedUid, id)
        return if (deleted) {
            ApiResponse(200, "Room deleted", null)
        } else {
            ApiResponse(404, "Room not found", null)
        }
    }

    /**
     * Updates the mutable fields of the authenticated school's profile.
     *
     * Accepts a [School] object but only applies [School.name], [School.phoneNumber],
     * [School.county], and [School.subCounty]. Identity fields ([School.fedUid] and
     * [School.email]) in the request body are ignored — the stored values are never
     * overwritten. Omitting a field (null) leaves the existing stored value unchanged.
     *
     * @param requestContext the JAX-RS request context carrying the `fedUid` property
     *                       set by [com.grandtech.auth.AuthFilter]
     * @param school         the [School] object containing the fields to update
     * @return an [ApiResponse] carrying the updated [School] on success, or 404 if
     *         no school node is found for the authenticated UID
     */
    @PATCH
    @Path("/profile")
    @Authenticated
    @Consumes(MediaType.APPLICATION_JSON)
    @Produces(MediaType.APPLICATION_JSON)
    fun updateSchoolDetails(
        @Context requestContext: ContainerRequestContext,
        school: School,
    ): ApiResponse<School> {
        val fedUid = requestContext.getProperty("fedUid") as String
        val updated = schoolService.updateSchool(fedUid, school)
        return if (updated != null) {
            ApiResponse(200, "Success", updated)
        } else {
            ApiResponse(404, "School not found", null)
        }
    }
}
