package com.grandtech.service

import com.grandtech.model.Room
import com.grandtech.model.RoomCapabilityTag
import jakarta.enterprise.context.ApplicationScoped
import jakarta.inject.Inject
import org.neo4j.driver.Driver
import org.neo4j.driver.Record

/** Executes Neo4j read and write operations specific to [Room] nodes. */
@ApplicationScoped
class RoomService {

    @Inject
    lateinit var driver: Driver

    /**
     * Creates a [Room] node in Neo4j and links it to the school identified by [schoolFedUid]
     * via a `HAS_ROOM` relationship. The room's [Room.id] is generated by Neo4j using
     * `randomUUID()` — callers must not supply one.
     *
     * Returns null if no `School` node exists for [schoolFedUid].
     */
    fun createRoom(schoolFedUid: String, room: Room): Room? =
        driver.session().use { session ->
            val result = session.run(
                """
                MATCH (s:School {fedUid: ${'$'}fedUid})
                CREATE (r:Room {
                    id: randomUUID(),
                    name: ${'$'}name,
                    capacity: ${'$'}capacity,
                    capabilityTag: ${'$'}capabilityTag,
                    isStandardClassroom: ${'$'}isStandardClassroom
                })
                CREATE (s)-[:HAS_ROOM]->(r)
                RETURN r.id AS id, r.name AS name, r.capacity AS capacity,
                       r.capabilityTag AS capabilityTag, r.isStandardClassroom AS isStandardClassroom
                """.trimIndent(),
                mapOf(
                    "fedUid"              to schoolFedUid,
                    "name"                to room.name,
                    "capacity"            to room.capacity,
                    "capabilityTag"       to room.capabilityTag?.name,
                    "isStandardClassroom" to room.isStandardClassroom,
                ),
            )
            if (result.hasNext()) mapToRoom(result.next()) else null
        }

    /**
     * Returns all [Room] nodes belonging to the school identified by [schoolFedUid],
     * ordered by name. Returns an empty list when the school has no rooms.
     */
    fun listRooms(schoolFedUid: String): List<Room> =
        driver.session().use { session ->
            session.run(
                """
                MATCH (s:School {fedUid: ${'$'}fedUid})-[:HAS_ROOM]->(r:Room)
                RETURN r.id AS id, r.name AS name, r.capacity AS capacity,
                       r.capabilityTag AS capabilityTag, r.isStandardClassroom AS isStandardClassroom
                ORDER BY r.name
                """.trimIndent(),
                mapOf("fedUid" to schoolFedUid),
            ).list { mapToRoom(it) }
        }

    /**
     * Updates the mutable fields of a [Room] node owned by the given school.
     *
     * [Room.id] is immutable and is never changed. Each field uses COALESCE so a null
     * value in [room] leaves the stored value unchanged. Returns null if no room with
     * [roomId] belongs to the school.
     */
    fun updateRoom(schoolFedUid: String, roomId: String, room: Room): Room? =
        driver.session().use { session ->
            val result = session.run(
                """
                MATCH (s:School {fedUid: ${'$'}fedUid})-[:HAS_ROOM]->(r:Room {id: ${'$'}roomId})
                SET r.name                = COALESCE(${'$'}name, r.name),
                    r.capacity            = COALESCE(${'$'}capacity, r.capacity),
                    r.capabilityTag       = COALESCE(${'$'}capabilityTag, r.capabilityTag),
                    r.isStandardClassroom = COALESCE(${'$'}isStandardClassroom, r.isStandardClassroom)
                RETURN r.id AS id, r.name AS name, r.capacity AS capacity,
                       r.capabilityTag AS capabilityTag, r.isStandardClassroom AS isStandardClassroom
                """.trimIndent(),
                mapOf(
                    "fedUid"              to schoolFedUid,
                    "roomId"              to roomId,
                    "name"                to room.name,
                    "capacity"            to room.capacity,
                    "capabilityTag"       to room.capabilityTag?.name,
                    "isStandardClassroom" to room.isStandardClassroom,
                ),
            )
            if (result.hasNext()) mapToRoom(result.next()) else null
        }

    /**
     * Deletes the [Room] node with [roomId] only if it is linked to the school
     * identified by [schoolFedUid] via a `HAS_ROOM` relationship.
     *
     * Uses `DETACH DELETE` so all relationships are removed with the node.
     * Returns false if the room was not found under this school.
     */
    fun deleteRoom(schoolFedUid: String, roomId: String): Boolean =
        driver.session().use { session ->
            val result = session.run(
                """
                MATCH (s:School {fedUid: ${'$'}fedUid})-[:HAS_ROOM]->(r:Room {id: ${'$'}roomId})
                DETACH DELETE r
                """.trimIndent(),
                mapOf("fedUid" to schoolFedUid, "roomId" to roomId),
            )
            result.consume().counters().nodesDeleted() > 0
        }

    private fun mapToRoom(record: Record) = Room(
        id                  = record["id"].takeUnless { it.isNull }?.asString(),
        name                = record["name"].takeUnless { it.isNull }?.asString(),
        capacity            = record["capacity"].takeUnless { it.isNull }?.asInt(),
        capabilityTag       = record["capabilityTag"].takeUnless { it.isNull }
                                ?.asString()?.let { RoomCapabilityTag.valueOf(it) },
        isStandardClassroom = record["isStandardClassroom"].takeUnless { it.isNull }?.asBoolean(),
    )
}