package com.grandtech.service

import com.grandtech.model.Room
import com.grandtech.model.RoomCapabilityTag
import com.grandtech.model.School
import jakarta.enterprise.context.ApplicationScoped
import jakarta.inject.Inject
import org.neo4j.driver.Driver
import org.neo4j.driver.Record

/**
 * Executes Neo4j read and write operations specific to [School] nodes.
 *
 * Immutable identity fields (`fedUid`, `email`) are never overwritten by updates.
 */
@ApplicationScoped
class SchoolService {

    /** Neo4j driver injected by Quarkus CDI; manages connection pooling and sessions. */
    @Inject
    lateinit var driver: Driver

    /**
     * Looks up a [School] node by its Firebase UID.
     *
     * Returns null if no `School` node exists with the given UID. A `Teacher`
     * node with the same UID will not match because the query targets the
     * `School` label specifically.
     *
     * @param fedUid the Firebase Authentication UID to search for
     * @return the matching [School], or null if no school node is found
     */
    fun getSchoolByFedUid(fedUid: String): School? =
        driver.session().use { session ->
            val result = session.run(
                "MATCH (s:School {fedUid: \$fedUid}) " +
                    "RETURN s.fedUid AS fedUid, s.name AS name, s.email AS email, " +
                    "s.phoneNumber AS phoneNumber, s.county AS county, s.subCounty AS subCounty",
                mapOf("fedUid" to fedUid),
            )
            if (result.hasNext()) {
                val record = result.next()
                School(
                    fedUid = record["fedUid"].asString(),
                    name = record["name"].takeUnless { it.isNull }?.asString(),
                    email = record["email"].takeUnless { it.isNull }?.asString(),
                    phoneNumber = record["phoneNumber"].takeUnless { it.isNull }?.asString(),
                    county = record["county"].takeUnless { it.isNull }?.asString(),
                    subCounty = record["subCounty"].takeUnless { it.isNull }?.asString(),
                )
            } else null
        }

    /**
     * Updates the mutable fields of a [School] node identified by [fedUid].
     *
     * Only [School.name], [School.phoneNumber], [School.county], and
     * [School.subCounty] are written. [School.fedUid] and [School.email]
     * are identity fields and are never modified. Each field uses COALESCE
     * so a null value in [school] leaves the stored value unchanged.
     *
     * @param fedUid the Firebase UID identifying the school node to update
     * @param school the [School] object carrying the new field values
     * @return the updated [School] as persisted in the graph, or null if no
     *         school node exists for the given [fedUid]
     */
    fun updateSchool(fedUid: String, school: School): School? =
        driver.session().use { session ->
            val result = session.run(
                """
                MATCH (s:School {fedUid: ${'$'}fedUid})
                SET s.name        = COALESCE(${'$'}name, s.name),
                    s.phoneNumber = COALESCE(${'$'}phoneNumber, s.phoneNumber),
                    s.county      = COALESCE(${'$'}county, s.county),
                    s.subCounty   = COALESCE(${'$'}subCounty, s.subCounty)
                RETURN s.fedUid AS fedUid, s.name AS name, s.email AS email,
                       s.phoneNumber AS phoneNumber, s.county AS county, s.subCounty AS subCounty
                """.trimIndent(),
                mapOf(
                    "fedUid"      to fedUid,
                    "name"        to school.name,
                    "phoneNumber" to school.phoneNumber,
                    "county"      to school.county,
                    "subCounty"   to school.subCounty,
                ),
            )
            if (result.hasNext()) {
                val record = result.next()
                School(
                    fedUid      = record["fedUid"].asString(),
                    name        = record["name"].takeUnless { it.isNull }?.asString(),
                    email       = record["email"].takeUnless { it.isNull }?.asString(),
                    phoneNumber = record["phoneNumber"].takeUnless { it.isNull }?.asString(),
                    county      = record["county"].takeUnless { it.isNull }?.asString(),
                    subCounty   = record["subCounty"].takeUnless { it.isNull }?.asString(),
                )
            } else null
        }

    /**
     * Creates a [Room] node in Neo4j and links it to the school identified by [schoolFedUid]
     * via a `HAS_ROOM` relationship. The room's [Room.id] is generated by Neo4j using
     * `randomUUID()` — callers must not supply one.
     *
     * Returns null if no `School` node exists for [schoolFedUid].
     *
     * @param schoolFedUid the Firebase UID of the owning school
     * @param room         the room data to persist (id is ignored)
     * @return the created [Room] with its generated id, or null if the school was not found
     */
    fun createRoom(schoolFedUid: String, room: Room): Room? =
        driver.session().use { session ->
            val result = session.run(
                """
                MATCH (s:School {fedUid: ${'$'}fedUid})
                CREATE (r:Room {
                    id: randomUUID(),
                    name: ${'$'}name,
                    capacity: ${'$'}capacity,
                    capabilityTag: ${'$'}capabilityTag,
                    isStandardClassroom: ${'$'}isStandardClassroom
                })
                CREATE (s)-[:HAS_ROOM]->(r)
                RETURN r.id AS id, r.name AS name, r.capacity AS capacity,
                       r.capabilityTag AS capabilityTag, r.isStandardClassroom AS isStandardClassroom
                """.trimIndent(),
                mapOf(
                    "fedUid"              to schoolFedUid,
                    "name"                to room.name,
                    "capacity"            to room.capacity,
                    "capabilityTag"       to room.capabilityTag?.name,
                    "isStandardClassroom" to room.isStandardClassroom,
                ),
            )
            if (result.hasNext()) mapToRoom(result.next()) else null
        }

    /**
     * Returns all [Room] nodes belonging to the school identified by [schoolFedUid],
     * ordered by name. Returns an empty list when the school has no rooms.
     *
     * @param schoolFedUid the Firebase UID of the school whose rooms to fetch
     * @return list of rooms owned by the school
     */
    fun listRooms(schoolFedUid: String): List<Room> =
        driver.session().use { session ->
            session.run(
                """
                MATCH (s:School {fedUid: ${'$'}fedUid})-[:HAS_ROOM]->(r:Room)
                RETURN r.id AS id, r.name AS name, r.capacity AS capacity,
                       r.capabilityTag AS capabilityTag, r.isStandardClassroom AS isStandardClassroom
                ORDER BY r.name
                """.trimIndent(),
                mapOf("fedUid" to schoolFedUid),
            ).list { mapToRoom(it) }
        }

    /**
     * Updates the mutable fields of a [Room] node owned by the given school.
     *
     * [Room.id] is the immutable identifier and is never changed. Each field uses
     * COALESCE so a null value in [room] leaves the stored value unchanged.
     * Returns null if no room with [roomId] belongs to the school.
     *
     * @param schoolFedUid the Firebase UID of the owning school
     * @param roomId       the UUID of the room to update
     * @param room         the new field values (null fields are ignored)
     * @return the updated [Room] as persisted, or null if the room was not found
     */
    fun updateRoom(schoolFedUid: String, roomId: String, room: Room): Room? =
        driver.session().use { session ->
            val result = session.run(
                """
                MATCH (s:School {fedUid: ${'$'}fedUid})-[:HAS_ROOM]->(r:Room {id: ${'$'}roomId})
                SET r.name               = COALESCE(${'$'}name, r.name),
                    r.capacity           = COALESCE(${'$'}capacity, r.capacity),
                    r.capabilityTag      = COALESCE(${'$'}capabilityTag, r.capabilityTag),
                    r.isStandardClassroom = COALESCE(${'$'}isStandardClassroom, r.isStandardClassroom)
                RETURN r.id AS id, r.name AS name, r.capacity AS capacity,
                       r.capabilityTag AS capabilityTag, r.isStandardClassroom AS isStandardClassroom
                """.trimIndent(),
                mapOf(
                    "fedUid"              to schoolFedUid,
                    "roomId"              to roomId,
                    "name"                to room.name,
                    "capacity"            to room.capacity,
                    "capabilityTag"       to room.capabilityTag?.name,
                    "isStandardClassroom" to room.isStandardClassroom,
                ),
            )
            if (result.hasNext()) mapToRoom(result.next()) else null
        }

    private fun mapToRoom(record: Record) = Room(
        id                  = record["id"].takeUnless { it.isNull }?.asString(),
        name                = record["name"].takeUnless { it.isNull }?.asString(),
        capacity            = record["capacity"].takeUnless { it.isNull }?.asInt(),
        capabilityTag       = record["capabilityTag"].takeUnless { it.isNull }
                                ?.asString()?.let { RoomCapabilityTag.valueOf(it) },
        isStandardClassroom = record["isStandardClassroom"].takeUnless { it.isNull }?.asBoolean(),
    )
}
