package com.grandtech.repository

import com.grandtech.model.Room
import com.grandtech.model.RoomCapabilityTag
import jakarta.enterprise.context.ApplicationScoped
import jakarta.inject.Inject
import org.neo4j.driver.Driver
import org.neo4j.driver.Record
import org.neo4j.driver.types.Node

/** Executes all Neo4j read and write operations specific to [Room] nodes. */
@ApplicationScoped
class RoomRepository {

    /** Neo4j driver injected by Quarkus CDI; manages connection pooling and sessions. */
    @Inject
    lateinit var driver: Driver

    /**
     * Creates a [Room] node linked to the school via `HAS_ROOM`.
     * The room's [Room.id] is generated by Neo4j — callers must not supply one.
     * Returns null if no school exists for [schoolFedUid].
     */
    fun createRoom(schoolFedUid: String, room: Room): Room? =
        driver.session().use { session ->
            val result = session.run(
                """
                MATCH (s:School {fedUid: ${'$'}fedUid})
                CREATE (r:Room {
                    id:                  randomUUID(),
                    name:                ${'$'}name,
                    capacity:            ${'$'}capacity,
                    capabilityTag:       ${'$'}capabilityTag,
                    isStandardClassroom: ${'$'}isStandardClassroom
                })
                CREATE (s)-[:HAS_ROOM]->(r)
                RETURN r.id AS id, r.name AS name, r.capacity AS capacity,
                       r.capabilityTag AS capabilityTag,
                       r.isStandardClassroom AS isStandardClassroom
                """.trimIndent(),
                mapOf(
                    "fedUid"              to schoolFedUid,
                    "name"                to room.name,
                    "capacity"            to room.capacity,
                    "capabilityTag"       to room.capabilityTag?.name,
                    "isStandardClassroom" to room.isStandardClassroom,
                ),
            )
            if (result.hasNext()) mapToRoom(result.next()) else null
        }

    /**
     * Returns all rooms belonging to [schoolFedUid], ordered by name.
     * Returns an empty list when the school has no rooms.
     */
    fun listRooms(schoolFedUid: String): List<Room> =
        driver.session().use { session ->
            session.run(
                """
                MATCH (s:School {fedUid: ${'$'}fedUid})-[:HAS_ROOM]->(r:Room)
                RETURN r.id AS id, r.name AS name, r.capacity AS capacity,
                       r.capabilityTag AS capabilityTag,
                       r.isStandardClassroom AS isStandardClassroom
                ORDER BY r.name
                """.trimIndent(),
                mapOf("fedUid" to schoolFedUid),
            ).list { mapToRoom(it) }.filterNotNull()
        }

    /**
     * Updates the mutable fields of a room owned by [schoolFedUid].
     * COALESCE ensures a null field in [room] leaves the stored value unchanged.
     * Returns null if no room with [roomId] belongs to the school.
     */
    fun updateRoom(schoolFedUid: String, roomId: String, room: Room): Room? =
        driver.session().use { session ->
            val result = session.run(
                """
                MATCH (s:School {fedUid: ${'$'}fedUid})-[:HAS_ROOM]->(r:Room {id: ${'$'}roomId})
                SET r.name                = COALESCE(${'$'}name, r.name),
                    r.capacity            = COALESCE(${'$'}capacity, r.capacity),
                    r.capabilityTag       = COALESCE(${'$'}capabilityTag, r.capabilityTag),
                    r.isStandardClassroom = COALESCE(${'$'}isStandardClassroom, r.isStandardClassroom)
                RETURN r.id AS id, r.name AS name, r.capacity AS capacity,
                       r.capabilityTag AS capabilityTag,
                       r.isStandardClassroom AS isStandardClassroom
                """.trimIndent(),
                mapOf(
                    "fedUid"              to schoolFedUid,
                    "roomId"              to roomId,
                    "name"                to room.name,
                    "capacity"            to room.capacity,
                    "capabilityTag"       to room.capabilityTag?.name,
                    "isStandardClassroom" to room.isStandardClassroom,
                ),
            )
            if (result.hasNext()) mapToRoom(result.next()) else null
        }

    /**
     * Deletes the room with [roomId] owned by [schoolFedUid] via `DETACH DELETE`.
     * Returns false if the room was not found under this school.
     */
    fun deleteRoom(schoolFedUid: String, roomId: String): Boolean =
        driver.session().use { session ->
            val result = session.run(
                """
                MATCH (s:School {fedUid: ${'$'}fedUid})-[:HAS_ROOM]->(r:Room {id: ${'$'}roomId})
                DETACH DELETE r
                """.trimIndent(),
                mapOf("fedUid" to schoolFedUid, "roomId" to roomId),
            )
            result.consume().counters().nodesDeleted() > 0
        }

    /**
     * Maps a Neo4j [Record] to a [Room].
     *
     * [prefix] supports reuse across queries that alias room columns differently:
     * - `prefix = ""`     → columns `id`, `name`, `capacity`, …  (direct room queries)
     * - `prefix = "room"` → columns `roomId`, `roomName`, `roomCapacity`, … (join queries)
     *
     * Returns null when the sentinel column `<prefix>id` is null, which indicates that
     * no room relationship was present in the result row.
     */
    internal fun mapToRoom(record: Record, prefix: String = ""): Room? =
        record[col(prefix, "id")].takeUnless { it.isNull }?.asString()?.let { id ->
            Room(
                id                  = id,
                name                = record[col(prefix, "name")].takeUnless { it.isNull }?.asString(),
                capacity            = record[col(prefix, "capacity")].takeUnless { it.isNull }?.asInt(),
                capabilityTag       = record[col(prefix, "capabilityTag")].takeUnless { it.isNull }
                                        ?.asString()?.let { RoomCapabilityTag.valueOf(it) },
                isStandardClassroom = record[col(prefix, "isStandardClassroom")].takeUnless { it.isNull }?.asBoolean(),
            )
        }

    /**
     * Maps a Neo4j [Node] (returned as a whole node via `RETURN r`) to a [Room].
     * Returns null when [node] is null, which indicates no `HOME_ROOM` relationship existed.
     */
    internal fun mapNodeToRoom(node: Node): Room =
        Room(
            id                  = node["id"].takeUnless { it.isNull }?.asString(),
            name                = node["name"].takeUnless { it.isNull }?.asString(),
            capacity            = node["capacity"].takeUnless { it.isNull }?.asInt(),
            capabilityTag       = node["capabilityTag"].takeUnless { it.isNull }
                                    ?.asString()?.let { RoomCapabilityTag.valueOf(it) },
            isStandardClassroom = node["isStandardClassroom"].takeUnless { it.isNull }?.asBoolean(),
        )

    /** Builds a column alias: empty prefix → `"id"`, prefix `"room"` → `"roomId"`. */
    private fun col(prefix: String, field: String) =
        if (prefix.isEmpty()) field else prefix + field.replaceFirstChar { it.uppercase() }
}