package com.grandtech.model

import com.fasterxml.jackson.annotation.JsonProperty

/**
 * A physical teaching space belonging to a school.
 *
 * Stored in Neo4j as a `Room` node linked via `(:School)-[:HAS_ROOM]->(:Room)`.
 * [capabilityTag] is null for standard classrooms and set for specialist rooms
 * (labs, workshops, etc.). It is matched against [Subject.roomCapabilityTag]
 * during post-solve room allocation.
 */
data class Room(
    /** UUID generated by Neo4j on creation. Null before the node is persisted. */
    val id: String? = null,

    /** Human-readable name, e.g. "Science Lab 1". */
    val name: String? = null,

    /** Maximum student capacity. */
    val capacity: Int? = null,

    /** Specialist facility type. Null for standard classrooms. */
    val capabilityTag: RoomCapabilityTag? = null,

    /** True when this room is a general-purpose classroom. */
    @get:JsonProperty("isStandardClassroom")
    val isStandardClassroom: Boolean? = null,
)