package com.grandtech.model

/**
 * A named class group within a JSS grade level, e.g. "Grade 7 Blue".
 *
 * A school organises students into streams per grade: Grade 7 can have streams
 * Blue, White, Red, etc. Each stream is an independent scheduling unit with its
 * own timetable.
 *
 * Stored in Neo4j as a `Stream` node with the following relationships:
 * - `(:School)-[:HAS_STREAM]->(:Stream)`
 * - `(:Stream)-[:FORM_TEACHER]->(:Teacher)` — one form teacher per stream (enforced on write)
 */
data class Stream(
    /** UUID generated by Neo4j on creation. Null before the node is persisted. */
    val id: String? = null,

    /** JSS grade level: 7, 8, or 9. */
    val gradeLevel: Int? = null,

    /** Stream name, e.g. "Blue", "White", "Red". */
    val name: String? = null,

    /** Approximate number of students (used for capacity checks). */
    val studentCount: Int? = null,

    /** Religious Education strand: CRE, IRE, or HRE. Null on create defaults to CRE via the service. */
    val reStrand: String? = null,

    /**
     * Form teacher assigned to this stream. On create, supply `{ "fedUid": "<uid>" }`;
     * the full [Teacher] object is returned in the response.
     * A teacher may only be form teacher for one stream at a time.
     */
    val formTeacher: Teacher? = null,
) {
    /** Returns a display label such as "Grade 7 Blue". */
    fun getDisplayName(): String = "Grade $gradeLevel $name"
}